apiVersion : apps/v1
kind: Deployment
metadata:
  name: zayanahmedpipelinesjavascriptdocker 
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: zayanahmedpipelinesjavascriptdocker
  template:
    metadata:
      labels:
        app: zayanahmedpipelinesjavascriptdocker 
    spec:
      containers:
        - name: zayanahmedpipelinesjavascriptdocker 
          image: mycontainerregistryforfipakstesting.azurecr.io/zayanahmedpipelinesjavascriptdocker
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
